#!/bin/bash -e

function archive_teslacam_clips () {
  log "Starting..."

  /root/bin/connect-archive.sh

  disconnect_usb_drives_from_host

  ensure_cam_file_is_mounted

  fix_errors_in_cam_file

  /root/bin/archive-clips.sh

  /root/bin/disconnect-archive.sh

  unmount_cam_file

  connect_usb_drives_to_host

}